# -*- coding: utf-8 -*-
"""task - 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oATZJkfvdGsuy9G0FsmXx1fOtAQg_v1d
"""

import random
import string

def generate_password(length):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

def main():
    print("Welcome to the Password Generator!")

    try:
        length = int(input("Enter the desired length of the password: "))
        if length <= 0:
            print("Please enter a valid positive length.")
            return
    except ValueError:
        print("Invalid input. Please enter a valid number for the length.")
        return

    password = generate_password(length)

    print(f"\nGenerated Password: {password}")

if __name__ == "__main__":
    main()